Architecture: "AttenRNN"

Seed: 42

Setting: kth

Logger:
    save_dir: "experiments/"

ckpt_path: None

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
    strategy: 'ddp'
    accelerator: 'gpu'
    log_every_n_steps: 64
    devices: [0, 1]  # 改动
    max_epochs: 200
    gradient_clip_val: 1

Data:
    context_length: 10
    target_length: 10
    val_length: 20
    val_batch_size: 16
    test_batch_size: 16
    train_batch_size: 16
    num_workers: 4

Task:
    loss:
        name: "MSE"

    context_length: 10
    target_length: 10
    val_length: 20
    n_stochastic_preds: 1
    metric: "PSNR"
    optimization:
        optimizer:
            - name: AdamW
              args:
                  betas: [ 0.9, 0.999]
              lr_per_sample: 0.00000625
        lr_shedule:
            - name: MultiStepLR
              args:
                  milestones: [3000] #[2, 20, 50, 90]
                  gamma: 0.1
    n_log_batches: 2


Model:
    patch_size: 8
    n_image: 1
    n_hidden: 256
    context_length: 10
    target_length: 10
    input_size: 128
    num_layers: 2
    fast_attn: True
    mlp_ratio: 4
    n_out: 1
    n_heads: 8
    depth: 2
    drop: 0.1
    attn_drop: 0.1
    drop_path: 0.1






