Architecture: "AttenRNN"

Seed: 42

Setting: human

Logger:
    save_dir: "experiments/"

ckpt_path: None

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
#    strategy: 'ddp'
    accelerator: 'gpu'
    log_every_n_steps: 64
    devices: [0]  # 改动
    max_epochs: 100
    gradient_clip_val: 1

Data:
    val_batch_size: 16
    test_batch_size: 16
    train_batch_size: 16
    context_length: 4
    target_length: 4
    num_workers: 4
    image_size: 128
    scene: "Walking"

Task:
    loss:
        name: "MSE"
        pred_mask_value: -1

    context_length: 4
    target_length: 4
    n_stochastic_preds: 1
    metric: "MSE"
    optimization:
        optimizer:
            - name: AdamW
              args:
                  betas: [ 0.9, 0.999]
              lr_per_sample: 0.00000625
        lr_shedule:
            - name: MultiStepLR
              args:
                  milestones: [100] #[2, 20, 50, 90]
                  gamma: 0.1
    n_log_batches: 2


Model:
    patch_size: 8
    n_image: 3
    n_hidden: 256
    context_length: 4
    target_length: 4
    input_size: 128
    num_layers: 3
    fast_attn: True
    mlp_ratio: 4
    n_out: 3
    n_heads: 8
    depth: 4
    drop: 0.1
    attn_drop: 0.1
    drop_path: 0.1





