Architecture: "DynamicNet_single"

Seed: 42

Setting: moving_mnist

Logger:
    save_dir: "experiments/"

ckpt_path: None

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
#    strategy: 'ddp'
    accelerator: 'gpu'
    log_every_n_steps: 64
    devices: [2]  # 改动
    max_epochs: 2000
    gradient_clip_val: 1

Data:
    train_batch_size: 16
    val_batch_size: 16
    test_batch_size: 16
    num_workers: 4

Task:
    loss:
        name: "MSE"

    context_length: 10
    target_length: 10
    n_stochastic_preds: 1
    metric: "MSE"
    optimization:
        optimizer:
            - name: AdamW
              args:
                  betas: [ 0.9, 0.999]
              lr_per_sample: 0.00000625
        lr_shedule:
            - name: MultiStepLR
              args:
                  milestones: [1000, 1500] #[2, 20, 50, 90]
                  gamma: 0.1
    n_log_batches: 2


Model:
    patch_size: 8
    n_image: 1
    n_hidden: 256
    context_length: 10
    target_length: 10
    input_size: 64
    n_out: 1
    n_heads: 8
    depth: 12
    drop: 0.0
    attn_drop: 0.0
    drop_path: 0.0
    field_size: [3, 5, 7]
    act: "silu"
    mtm: False
    leave_n_first: 3
    p_mtm: 0.7
    p_use_mtm: 0.5






